### PR TITLE
Resolves #7 (syntax error)

### LINKED ISSUE #7: Seems to be broken out of the box
I just installed this plugin and tried to run it with the exact configuration options specified in the README, and I get an error:

Here's the stack trace:

```
TypeError: undefined is not a function
    at createSharpPipeline (/Users/philipwalton/Projects/philipwalton/blog/node_modules/gulp-sharp/index.js:53:128)
    at gulpSharp (/Users/philipwalton/Projects/philipwalton/blog/node_modules/gulp-sharp/index.js:124:18)
    at Gulp.<anonymous> (/Users/philipwalton/Projects/philipwalton/blog/gulpfile.babel.js:286:13)
    at module.exports (/Users/philipwalton/Projects/philipwalton/blog/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/philipwalton/Projects/philipwalton/blog/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/philipwalton/Projects/philipwalton/blog/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/philipwalton/Projects/philipwalton/blog/node_modules/orchestrator/index.js:134:8)
    at /Users/philipwalton/Projects/philipwalton/blog/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

If I replace `undefined` at index.js:53:128 with `function() {}`, everything seems to work fine.

I'm using the latest version of gulp, node, and gulp-sharp on Mac OS X

### PR DESCRIPTION
**Pull request by katspaugh**
Maybe also think of adding some basic tests?

### CODE REVIEW

**Comment by valk91** [comment]
LGTM!

**Comment by rowanoulton** [comment]
+1 for merge

**Comment by jeremenichelli** [comment]
Please merge this!

**Comment by alexblunck** [comment]
+1

**Pull request merged**
